# Generated by Django 4.2.24 on 2026-05-10 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sigic_geonode.sigic_data_importer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IneiBaseLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer_type",
                    models.CharField(
                        choices=[("estado", "Estado"), ("municipio", "Municipio")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "geonode_dataset_id",
                    models.IntegerField(
                        help_text="Referencia al Dataset.id en GeoNode (sin constraint de FK)",
                        verbose_name="ID del Dataset en GeoNode",
                    ),
                ),
                (
                    "key_field",
                    models.CharField(
                        help_text="Nombre del campo clave INEGI en la capa (ej. CVE_GEO, CVEGEO)",
                        max_length=100,
                    ),
                ),
                (
                    "name_field",
                    models.CharField(
                        help_text="Nombre del campo de nombre geografico (ej. NOMGEO, NOM_ENT)",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "db_table": "sigic_data_importer_inei_base_layer",
            },
        ),
        migrations.CreateModel(
            name="DataImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("analyzing", "Analizando"),
                            ("ready", "Listo para configurar"),
                            ("importing", "Importando a GeoNode"),
                            ("done", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("original_filename", models.CharField(max_length=500)),
                (
                    "file_path",
                    models.FileField(
                        max_length=500,
                        upload_to=sigic_geonode.sigic_data_importer.models._upload_path,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel (.xlsx)"),
                            ("xls", "Excel (.xls)"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "column_schema",
                    models.JSONField(
                        blank=True,
                        help_text="Lista de {name, detected_type, confidence, sample_values, editable_type}",
                        null=True,
                    ),
                ),
                (
                    "geo_strategy",
                    models.CharField(
                        choices=[
                            ("latlon", "Coordenadas lat/lon"),
                            ("state_name", "Nombre de estado"),
                            ("mun_name", "Nombre de municipio"),
                            ("inegi_state_key", "Clave INEGI estado (2 digitos)"),
                            ("inegi_mun_key", "Clave INEGI municipio (5 digitos)"),
                            ("none", "Sin geometria"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                (
                    "geo_field_lat",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "geo_field_lon",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "geo_field_join",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("geonode_dataset_id", models.IntegerField(blank=True, null=True)),
                ("dashboard_site_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sigic_data_importer_job",
                "ordering": ["-created_at"],
            },
        ),
    ]
