# Generated by Django 4.2.24 on 2026-05-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigic_dashboard", "0003_site_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="info_text",
            field=models.TextField(
                blank=True,
                help_text="Opcional",
                null=True,
                verbose_name="Informacion de indicador",
            ),
        ),
        migrations.AlterField(
            model_name="indicatorfieldboxinfo",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Clase CSS de Font Awesome (e.g. 'fas fa-chart-bar')",
                max_length=100,
                verbose_name="Icono",
            ),
        ),
        migrations.AlterField(
            model_name="indicatorgroup",
            name="info_text",
            field=models.TextField(
                blank=True,
                help_text="Opcional",
                null=True,
                verbose_name="Informacion de grupo",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="info_text",
            field=models.TextField(
                blank=True,
                help_text="Opcional",
                null=True,
                verbose_name="Informacion de sitio",
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="info_text",
            field=models.TextField(
                blank=True,
                help_text="Opcional",
                null=True,
                verbose_name="Informacion de subgrupo",
            ),
        ),
    ]
