# Generated by Django 4.2.24 on 2026-06-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sigic_dashboard", "0007_site_is_public_default_false"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTopBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show",
                    models.BooleanField(default=False, verbose_name="Mostrar banda"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Título (lado izquierdo)",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff", max_length=40, verbose_name="Color de fondo"
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#333333", max_length=40, verbose_name="Color de texto"
                    ),
                ),
                ("height", models.IntegerField(default=60, verbose_name="Alto (px)")),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_bar",
                        to="sigic_dashboard.site",
                    ),
                ),
            ],
            options={
                "db_table": "sigic_dashboard_site_top_bar",
            },
        ),
        migrations.CreateModel(
            name="SiteTopBarLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="dashboard/top_bar_logos/",
                        verbose_name="Imagen subida",
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True, default="", verbose_name="URL externa de imagen"
                    ),
                ),
                (
                    "icon_link",
                    models.URLField(
                        blank=True, default="", verbose_name="Enlace al hacer clic"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Texto alternativo",
                    ),
                ),
                ("stack_order", models.IntegerField(default=1)),
                (
                    "top_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logos",
                        to="sigic_dashboard.sitetopbar",
                    ),
                ),
            ],
            options={
                "db_table": "sigic_dashboard_site_top_bar_logo",
                "ordering": ["stack_order"],
            },
        ),
    ]
