# Generated by Django 4.2.17 on 2025-06-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkWebSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "image",
                    models.ImageField(
                        upload_to="link_web_site/image/", verbose_name="Imagen"
                    ),
                ),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Link Web Site",
                "verbose_name_plural": "Links Web Site",
                "ordering": ["title"],
            },
        ),
    ]