# Generated by Django 4.2.24 on 2026-03-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigic_scenarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="zoom",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
