# Generated by Django 4.2.24 on 2026-06-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigic_requests", "0002_alter_requests_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requests",
            name="status",
            field=models.CharField(
                choices=[
                    ("on_review", "On review"),
                    ("pending", "Pending"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("editing", "Editing"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
