# Generated by Django 4.2.24 on 2026-03-20 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SigicMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="created on"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="modified on"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del mapa"),
                ),
                ("slug", models.SlugField(blank=True, max_length=30, unique=True)),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sigic_mapas/previews/",
                        verbose_name="Previsualizacion del mapa",
                    ),
                ),
                ("zoom", models.IntegerField(default=5, verbose_name="zoom")),
                (
                    "center_lat",
                    models.FloatField(default=-101.61, verbose_name="center X"),
                ),
                (
                    "center_long",
                    models.FloatField(default=22.21, verbose_name="center Y"),
                ),
                (
                    "map_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("swipe", "Swipe"),
                            ("dual", "Dual"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="Tipo de mapa",
                    ),
                ),
                (
                    "base_layer",
                    models.CharField(
                        default="osm", max_length=255, verbose_name="Capa base"
                    ),
                ),
                (
                    "highlight_color",
                    models.CharField(
                        default="#ff51ba",
                        max_length=255,
                        verbose_name="Color de resaltado",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapa Sigic",
                "verbose_name_plural": "Mapas Sigic",
                "db_table": "sigic_map",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MapLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="created on"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="modified on"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, verbose_name="Nombre de la capa en Geoserver"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Estilo de la capa"
                    ),
                ),
                (
                    "geonode_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID de referencia de la capa en GeoNode",
                        null=True,
                        verbose_name="Id de la capa en Geonode",
                    ),
                ),
                (
                    "map_position",
                    models.CharField(
                        choices=[("left", "Izquierda"), ("right", "Derecha")],
                        default="left",
                        max_length=10,
                        verbose_name="Posición en el mapa (si aplica)",
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True,
                        help_text="Si la capa esta visible en el mapa",
                        verbose_name="Visible",
                    ),
                ),
                (
                    "opacity",
                    models.FloatField(
                        default=1.0,
                        help_text="Opacidad de la capa (0.0 a 1.0)",
                        verbose_name="Opacidad",
                    ),
                ),
                (
                    "stack_order",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de las capas en el mapa (mayor = arriba)",
                        verbose_name="Orden de apilamiento",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="sigic_mapas.sigicmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capa de Mapa",
                "verbose_name_plural": "Capas de Mapa",
                "db_table": "sigic_map_layers",
                "ordering": ["stack_order"],
            },
        ),
    ]